/**
 * C client stub to invoke services exported by the XML-RPC component: sasl_radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __SASL_RADMIN_XML_RPC_TYPES_H__
#define __SASL_RADMIN_XML_RPC_TYPES_H__

/* SaslUser type declaration */
typedef struct __SaslUser SaslUser;

/* SaslUserArray type declaration */
typedef struct __SaslUserArray SaslUserArray;

/* SaslUser type interface */
#include <sasl_radmin_struct_sasluser_xml_rpc.h>

/* SaslUserArray type interface */
#include <sasl_radmin_array_sasluserarray_xml_rpc.h>


#endif
