/**
 * C server skel to implement services exported by the XML-RPC
 * component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#include <vortex.h>
#include <sasl_radmin_types.h>

SaslUserArray * get_users_1_string (const char * serverName, char ** fault_error, int * fault_code, VortexChannel * channel)
{
	

		/* not implemented yet */
		return NULL;
	
}

/* This is a support function to invoke 'get_users' service , do not modify it!! */
XmlRpcMethodResponse * __get_users_1_string (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	char * fault_error = NULL;
	int    fault_code  = -1;
	SaslUserArray *    result = NULL;

	XmlRpcArray * _result;
	/* call to the user implementation */
	result = get_users_1_string (method_call_get_param_value_as_string (method_call, 0),  &fault_error, &fault_code, channel);

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	if (result == NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (-2, "Returned a NULL value from a service which returns a pointer type. This is not allowed.");
	}

	/* Translate structure returned by the service */
	_result = sasl_radmin_sasluserarray_marshall (result, true);

	/* return reply generated */
	return CREATE_OK_REPLY (XML_RPC_ARRAY_VALUE, _result);
}
