/**
 * C server skel to implement services exported by the XML-RPC
 * component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#include <vortex.h>
#include <sasl_radmin_types.h>

/* external variables to implement the backend module */
extern SaslAuthBackend * sasl_backend;
extern VortexMutex       sasl_xml_db_mutex;

SaslUserArray * get_users_0 (char ** fault_error, int * fault_code, VortexChannel * channel)
{
	axlList          * list;
	VortexConnection * conn;

	/* get the serverName */
	const char       * serverName = SERVER_NAME_FROM_CHANNEL(channel);

	/* get the user list associated to the current serverName */
	list = common_sasl_get_users (sasl_backend, &sasl_xml_db_mutex);

	/* not implemented yet */
	return NULL;
	
}

/* This is a support function to invoke 'get_users' service , do not modify it!! */
XmlRpcMethodResponse * __get_users_0 (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	char * fault_error = NULL;
	int    fault_code  = -1;
	SaslUserArray *    result = NULL;

	XmlRpcArray * _result;
	/* call to the user implementation */
	result = get_users_0 ( &fault_error, &fault_code, channel);

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	if (result == NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (-2, "Returned a NULL value from a service which returns a pointer type. This is not allowed.");
	}

	/* Translate structure returned by the service */
	_result = sasl_radmin_sasluserarray_marshall (result, true);

	/* return reply generated */
	return CREATE_OK_REPLY (XML_RPC_ARRAY_VALUE, _result);
}
