/**
 * C server skel to implement services exported by the XML-RPC
 * component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <sasl_radmin_types.h>

/* code included from: get-users-include.c */
/* local includes */
#include <sasl_radmin_types.h>
#include <common-sasl.h>

/* external variables to implement the backend module */
extern SaslAuthBackend * sasl_backend;
extern VortexMutex       sasl_xml_db_mutex;

SaslUserArray * get_users_0 (char ** fault_error, int * fault_code, VortexChannel * channel)
{
	
		axlList          * list;
		SaslUserArray    * users;
		SaslUser         * user;
		
		/* get the serverName */
		const char       * serverName = SERVER_NAME_FROM_CHANNEL(channel);
		
		/* get the user list associated to the current serverName */
		list     = common_sasl_get_users (sasl_backend, serverName, &sasl_xml_db_mutex);
		users    = sasl_radmin_sasluserarray_new (axl_list_length (list));
		while (axl_list_length (list) > 0) {
			/* get a user */
			user = axl_list_get_first (list);
			
			/* store in the array */
			sasl_radmin_sasluserarray_add (users, user);
			
			/* unlink from the list */
			axl_list_unlink_first (list);
			
		} /* end list */
		axl_list_free (list);
		
		/* not implemented yet */
		return users;
	
}

/* This is a support function to invoke 'get_users' service , do not modify it!! */
XmlRpcMethodResponse * __get_users_0 (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	VortexCtx * ctx         = METHOD_CALL_CTX(method_call);
	char      * fault_error = NULL;
	int         fault_code  = -1;
	SaslUserArray *    result = NULL;

	XmlRpcArray * _result;
	/* call to the user implementation */
	result = get_users_0 ( &fault_error, &fault_code, channel);

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	if (result == NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (-2, "Returned a NULL value from a service which returns a pointer type. This is not allowed.");
	}

	/* Translate structure returned by the service */
	_result = sasl_radmin_sasluserarray_marshall (ctx, result, axl_true);

	/* return reply generated */
	return CREATE_OK_REPLY (ctx, XML_RPC_ARRAY_VALUE, _result);
}
