/**
 * C client stub to invoke services exported by the XML-RPC component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __XML_RPC_STRUCT_SASLUSER_H__
#define __XML_RPC_STRUCT_SASLUSER_H__

/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <sasl_radmin_types.h>

/* SaslUser type declaration */
/* user definition declared at: sasl_radmin_types.h */
struct __SaslUser {
	char * auth_id;
	bool disabled;
};

/* support for c++ declarations */
BEGIN_C_DECLS

/* (un)marshaller support functions  */
XmlRpcStruct * sasl_radmin_sasluser_marshall (SaslUser * ref, bool dealloc);
SaslUser * sasl_radmin_sasluser_unmarshall (XmlRpcStruct * ref, bool dealloc);

/* memory (de)allocation functions */
SaslUser * sasl_radmin_sasluser_new (const char * auth_id, bool disabled);

SaslUser * sasl_radmin_sasluser_copy (SaslUser * ref);

void sasl_radmin_sasluser_free (SaslUser * ref);

END_C_DECLS

#endif
