# -*- makefile -*- mode 
# Makefile for windows (mingw)

# object files
obj  = test_01.o

# resulting programa
program = test_01.exe

# libraries 
LIBS = -Wall -g \
	-L"../../libaxl/src/" -L"../../libvortex-1.1/src/" -L"../../libexarg/src" \
	-L"../src" -lturbulence \
	-lvortex-1.1 -laxl -lexarg -lws2_32 $(OPENSSL_LIBS) $(GSASL_LIBS) $(PCRE_LIBS) $(search_lib_path) 

# build vortex with log support
INCS =  -Wall -g -I"." -I"../../libaxl/src" -I"../../libvortex-1.1/src" -I"../../libexarg/src" -I"../src" \
	-I"../modules/mod-sasl" 

CFLAGS = $(INCS) -DVERSION=\""$(TURBULENCE_VERSION)"\" -DVORTEX_VERSION=\""$(VORTEX_VERSION)"\" -DAXL_VERSION=\""$(AXL_VERSION)"\" \
	-DPACKAGE_DTD_DIR=\""$(datadir)"\" -DPACKAGE_TOP_DIR=\""$(top_srcdir)"\" -Wall -g $(OPENSSL_FLAGS) $(GSASL_FLAGS) $(PCRE_FLAGS) \
	-DCOMPILATION_DATE=`date +%s` -D__COMPILING_TURBULENCE__ 
RM = rm -f

.PHONY: all clean

all: $(program) links

clean: 
	${RM} $(obj) $(program)

$(program): $(obj)
	$(CC) -mconsole $(obj) ../modules/mod-sasl/common-sasl.o -o $@ $(LIBS)

links:
	cp ../../libvortex-1.1/src/libvortex-1.1.dll .
	cp ../../libvortex-1.1/data/*.dtd .
	cp ../../libaxl/src/libaxl.dll .
	cp ../../libexarg/src/libexarg.dll .
	cp ../src/libturbulence.dll .
	cp $(OPENSSL_LIBS) .
	cp $(PCRE_FILES) .

%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)
