/**
 * C server skel to implement services exported by the XML-RPC
 * component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#include <vortex.h>
#include <sasl_radmin_types.h>

/* local includes */
#include <sasl_radmin_types.h>
#include <common-sasl.h>

/* external variables to implement the backend module */
extern SaslAuthBackend * sasl_backend;
extern VortexMutex       sasl_xml_db_mutex;


int operate_sasl_user_3_string_string_int (const char * auth_id, const char * additional_value, int operation, char ** fault_error, int * fault_code, VortexChannel * channel)
{
	/* get the serverName from the current channel */
	const char * serverName = SERVER_NAME_FROM_CHANNEL(channel);
	
	switch (operation) {
	case 1:
		/* add create a new sasl user */
		return common_sasl_user_add (sasl_backend, 
					     /* sasl user */
					     auth_id,
					     /* sasl password */
					     additional_value,
					     /* no server name */
					     serverName,
					     /* mutex */
					     &sasl_xml_db_mutex);
	case 2:
		/* remove a paritcular sasl user */
		return common_sasl_user_remove (sasl_backend, 
						/* sasl user */
						auth_id,
						/* no server name */
						serverName,
						/* mutex */
						&sasl_xml_db_mutex);

	case 3:
		/* change user password */
		/* not implemented */
		break;
	case 4:
		/* edit user auth id */
		/* not implemented */
		break;
	case 5:
		/* make the user provided to have remote
		 * administration support */
		/* not implemented */
	default:
		/* operation not implemented */
		return false;
	}
	
	/* operation not implemented */
	return false;
}

/* This is a support function to invoke 'operate_sasl_user' service , do not modify it!! */
XmlRpcMethodResponse * __operate_sasl_user_3_string_string_int (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	char * fault_error = NULL;
	int    fault_code  = -1;
	int    result = false;

	/* call to the user implementation */
	result = operate_sasl_user_3_string_string_int (method_call_get_param_value_as_string (method_call, 0), method_call_get_param_value_as_string (method_call, 1), method_call_get_param_value_as_int (method_call, 2),  &fault_error, &fault_code, channel);

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	/* return reply generated */
	return CREATE_OK_REPLY (XML_RPC_BOOLEAN_VALUE, INT_TO_PTR (result));
}
