/**
 * C client stub to invoke services exported by the XML-RPC component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#include <sasl_radmin_types.h>

/* (un)marshaller support functions  */
XmlRpcStruct * sasl_radmin_sasluser_marshall (SaslUser * ref, bool dealloc)
{
	XmlRpcStruct       * _result;
	XmlRpcStructMember * _member;

	/* check received reference */
	if (ref == NULL)
		return NULL;
	/* create the struct */
	_result = vortex_xml_rpc_struct_new (2);

	/* auth_id member */
	_member = vortex_xml_rpc_struct_member_new ("auth_id", method_value_new (XML_RPC_STRING_VALUE, ref->auth_id ? ref->auth_id : ""));
	vortex_xml_rpc_struct_add_member (_result, _member);

	/* disabled member */
	_member = vortex_xml_rpc_struct_member_new ("disabled", method_value_new (XML_RPC_BOOLEAN_VALUE, INT_TO_PTR (ref->disabled)));
	vortex_xml_rpc_struct_add_member (_result, _member);

	/* dealloc data source */
	if (dealloc)
		sasl_radmin_sasluser_free (ref);

	/* return result created */
	return _result;
}

SaslUser * sasl_radmin_sasluser_unmarshall (XmlRpcStruct * ref, bool dealloc)
{
	SaslUser * _result;

	/* check received reference */
	if (ref == NULL)
		return NULL;

	/* check the number of items the provided struct */
	v_return_val_if_fail (vortex_xml_rpc_struct_get_member_count (ref) == 2, NULL);
	/* check member names */
	v_return_val_if_fail (vortex_xml_rpc_struct_check_member_names (ref, 2, "auth_id", "disabled"), NULL);
	/* check member types */
	v_return_val_if_fail (vortex_xml_rpc_struct_check_member_types (ref, 2, "string", "bool"), NULL);

	_result = sasl_radmin_sasluser_new (
		vortex_xml_rpc_struct_get_member_value_as_string (ref, "auth_id"),
		vortex_xml_rpc_struct_get_member_value_as_int (ref, "disabled"));

	/* dealloc data source */
	if (dealloc)
		vortex_xml_rpc_struct_free (ref);

	return _result;
}

/* memory (de)allocation functions */
SaslUser * sasl_radmin_sasluser_new (const char * auth_id, bool disabled)
{
	SaslUser * _result = axl_new (SaslUser, 1);

	_result->auth_id = axl_strdup (auth_id);
	_result->disabled = disabled;
	
	return _result;
}

SaslUser * sasl_radmin_sasluser_copy (SaslUser * ref)
{
	SaslUser * _result = NULL;

	if (ref == NULL)
		return NULL;

	_result = axl_new (SaslUser, 1);
	_result->auth_id = axl_strdup (ref->auth_id);
	_result->disabled = ref->disabled;
	
	return _result;
}

void sasl_radmin_sasluser_free (SaslUser * ref)
{
	if (ref == NULL)
		return;
	if (ref->auth_id)
		axl_free (ref->auth_id);
	if (ref != NULL)
		axl_free (ref);
	return;
}

