/**
 * C client stub to invoke services exported by the XML-RPC component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __XML_RPC_ARRAY_SASLUSERARRAY_H__
#define __XML_RPC_ARRAY_SASLUSERARRAY_H__

/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <sasl_radmin_types.h>

/* support for c++ declarations */
BEGIN_C_DECLS

/* (un)marshaller support functions  */
XmlRpcArray    * sasl_radmin_sasluserarray_marshall   (SaslUserArray * ref, bool dealloc);
SaslUserArray * sasl_radmin_sasluserarray_unmarshall (XmlRpcArray * ref, bool dealloc);

/* memory (de)allocation functions */
SaslUserArray * sasl_radmin_sasluserarray_new  (int count);
void sasl_radmin_sasluserarray_free (SaslUserArray * ref);

/* manipulation functions */
SaslUser * sasl_radmin_sasluserarray_get (SaslUserArray * ref, int index);
void sasl_radmin_sasluserarray_set (SaslUserArray * ref, int index, SaslUser * value);
void sasl_radmin_sasluserarray_add (SaslUserArray * ref, SaslUser * value);

int sasl_radmin_sasluserarray_count (SaslUserArray * ref);

END_C_DECLS

#endif
