/**
 * C server skel to implement services exported by the XML-RPC
 * component: sasl-radmin.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#include <sasl_radmin_get_users.h>
#include <sasl_radmin_operate_sasl_user_string_string_bool_bool_int.h>


/* include xml-rpc library */
#include <vortex_xml_rpc.h>
XmlRpcMethodResponse *  service_dispatch (VortexChannel * channel, XmlRpcMethodCall * method_call, axlPointer user_data)
{

	/* check for a match for a service */
	/* handle all services under the resource=sasl-radmin */
	if (axl_cmp (vortex_xml_rpc_channel_get_resource (channel), "sasl-radmin")) {

		if (method_call_is (method_call, "get_users", 0,  -1))
			return __get_users_0 (method_call, channel);

		if (method_call_is (method_call, "operate_sasl_user", 5, XML_RPC_STRING_VALUE, XML_RPC_STRING_VALUE, XML_RPC_BOOLEAN_VALUE, XML_RPC_BOOLEAN_VALUE, XML_RPC_INT_VALUE,  -1))
			return __operate_sasl_user_5_string_string_bool_bool_int (method_call, channel);

		/* no more services under resource=sasl-radmin */
		return NULL;

	} /* end if */

	/* return that the method to be invoked, is not supported or recognized by this module */
	return NULL;
}

